package com.huaao.ejwplatform.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.huaao.ejwplatform.dao.JwEntity;
import com.huaao.ejwplatform.dao.JwEntityExample;
import com.huaao.ejwplatform.dao.JwEntityExt;

public interface JwEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_entity
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int countByExample(JwEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_entity
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int deleteByExample(JwEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_entity
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_entity
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int insert(JwEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_entity
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int insertSelective(JwEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_entity
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    List<JwEntity> selectByExample(JwEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_entity
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    JwEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_entity
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") JwEntity record, @Param("example") JwEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_entity
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int updateByExample(@Param("record") JwEntity record, @Param("example") JwEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_entity
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int updateByPrimaryKeySelective(JwEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_entity
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int updateByPrimaryKey(JwEntity record);
    
    List<JwEntityExt> selectByExampleExt(JwEntityExample example);

    JwEntityExt selectByPrimaryKeyExt(String id);
}