package com.huaao.ejwplatform.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.session.RowBounds;

import com.huaao.ejwplatform.dao.UserTest;
import com.huaao.ejwplatform.dao.UserTestExample;

public interface UserTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    int countByExample(UserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    int deleteByExample(UserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    int insert(UserTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    int insertSelective(UserTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    List<UserTest> selectByExample(UserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    UserTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserTest record, @Param("example") UserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    int updateByExample(@Param("record") UserTest record, @Param("example") UserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    int updateByPrimaryKeySelective(UserTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */ 
    int updateByPrimaryKey(UserTest record);
    
    
    @Select("SELECT id FROM user_test WHERE account = #{account} and password=#{password}")
	String test(@Param("account") String account
			,@Param("password") String password);
    
    List<UserTest> selectByExampleWithRowbounds(UserTestExample example, RowBounds rowBounds);

}