package com.huaao.ejwplatform.dao;

import java.io.Serializable;
import java.util.Date;

public class JwEmsPayResult implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_pay_result.id
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_pay_result.biz_order_no
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    private String bizOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_pay_result.pay_platform
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    private String payPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_pay_result.pay_way
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    private String payWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_pay_result.pay_amount
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    private String payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_pay_result.pay_result
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    private String payResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_pay_result.req_reserved
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    private String reqReserved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_pay_result.pay_time
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    private String payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_pay_result.user_pay_account
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    private String userPayAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_pay_result.order_time
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    private String orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_pay_result.refund_result
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    private String refundResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_pay_result.faild_reason
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    private String faildReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_pay_result.record_id
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_pay_result.create_time
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jw_ems_pay_result
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_pay_result.id
     *
     * @return the value of jw_ems_pay_result.id
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_pay_result.id
     *
     * @param id the value for jw_ems_pay_result.id
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_pay_result.biz_order_no
     *
     * @return the value of jw_ems_pay_result.biz_order_no
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public String getBizOrderNo() {
        return bizOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_pay_result.biz_order_no
     *
     * @param bizOrderNo the value for jw_ems_pay_result.biz_order_no
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public void setBizOrderNo(String bizOrderNo) {
        this.bizOrderNo = bizOrderNo == null ? null : bizOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_pay_result.pay_platform
     *
     * @return the value of jw_ems_pay_result.pay_platform
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public String getPayPlatform() {
        return payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_pay_result.pay_platform
     *
     * @param payPlatform the value for jw_ems_pay_result.pay_platform
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public void setPayPlatform(String payPlatform) {
        this.payPlatform = payPlatform == null ? null : payPlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_pay_result.pay_way
     *
     * @return the value of jw_ems_pay_result.pay_way
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public String getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_pay_result.pay_way
     *
     * @param payWay the value for jw_ems_pay_result.pay_way
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public void setPayWay(String payWay) {
        this.payWay = payWay == null ? null : payWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_pay_result.pay_amount
     *
     * @return the value of jw_ems_pay_result.pay_amount
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public String getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_pay_result.pay_amount
     *
     * @param payAmount the value for jw_ems_pay_result.pay_amount
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public void setPayAmount(String payAmount) {
        this.payAmount = payAmount == null ? null : payAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_pay_result.pay_result
     *
     * @return the value of jw_ems_pay_result.pay_result
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public String getPayResult() {
        return payResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_pay_result.pay_result
     *
     * @param payResult the value for jw_ems_pay_result.pay_result
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public void setPayResult(String payResult) {
        this.payResult = payResult == null ? null : payResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_pay_result.req_reserved
     *
     * @return the value of jw_ems_pay_result.req_reserved
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public String getReqReserved() {
        return reqReserved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_pay_result.req_reserved
     *
     * @param reqReserved the value for jw_ems_pay_result.req_reserved
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public void setReqReserved(String reqReserved) {
        this.reqReserved = reqReserved == null ? null : reqReserved.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_pay_result.pay_time
     *
     * @return the value of jw_ems_pay_result.pay_time
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public String getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_pay_result.pay_time
     *
     * @param payTime the value for jw_ems_pay_result.pay_time
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public void setPayTime(String payTime) {
        this.payTime = payTime == null ? null : payTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_pay_result.user_pay_account
     *
     * @return the value of jw_ems_pay_result.user_pay_account
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public String getUserPayAccount() {
        return userPayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_pay_result.user_pay_account
     *
     * @param userPayAccount the value for jw_ems_pay_result.user_pay_account
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public void setUserPayAccount(String userPayAccount) {
        this.userPayAccount = userPayAccount == null ? null : userPayAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_pay_result.order_time
     *
     * @return the value of jw_ems_pay_result.order_time
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_pay_result.order_time
     *
     * @param orderTime the value for jw_ems_pay_result.order_time
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime == null ? null : orderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_pay_result.refund_result
     *
     * @return the value of jw_ems_pay_result.refund_result
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public String getRefundResult() {
        return refundResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_pay_result.refund_result
     *
     * @param refundResult the value for jw_ems_pay_result.refund_result
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public void setRefundResult(String refundResult) {
        this.refundResult = refundResult == null ? null : refundResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_pay_result.faild_reason
     *
     * @return the value of jw_ems_pay_result.faild_reason
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public String getFaildReason() {
        return faildReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_pay_result.faild_reason
     *
     * @param faildReason the value for jw_ems_pay_result.faild_reason
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public void setFaildReason(String faildReason) {
        this.faildReason = faildReason == null ? null : faildReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_pay_result.record_id
     *
     * @return the value of jw_ems_pay_result.record_id
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_pay_result.record_id
     *
     * @param recordId the value for jw_ems_pay_result.record_id
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_pay_result.create_time
     *
     * @return the value of jw_ems_pay_result.create_time
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_pay_result.create_time
     *
     * @param createTime the value for jw_ems_pay_result.create_time
     *
     * @mbggenerated Wed Apr 19 16:37:59 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}