package com.huaao.ejwplatform.dao;

import java.io.Serializable;
import java.util.Date;

public class JwFunctionalDept implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_functional_dept.id
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_functional_dept.name
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_functional_dept.phone
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_functional_dept.remark
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_functional_dept.create_id
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_functional_dept.create_time
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_functional_dept.updater_id
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    private String updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_functional_dept.update_time
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jw_functional_dept
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_functional_dept.id
     *
     * @return the value of jw_functional_dept.id
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_functional_dept.id
     *
     * @param id the value for jw_functional_dept.id
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_functional_dept.name
     *
     * @return the value of jw_functional_dept.name
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_functional_dept.name
     *
     * @param name the value for jw_functional_dept.name
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_functional_dept.phone
     *
     * @return the value of jw_functional_dept.phone
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_functional_dept.phone
     *
     * @param phone the value for jw_functional_dept.phone
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_functional_dept.remark
     *
     * @return the value of jw_functional_dept.remark
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_functional_dept.remark
     *
     * @param remark the value for jw_functional_dept.remark
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_functional_dept.create_id
     *
     * @return the value of jw_functional_dept.create_id
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_functional_dept.create_id
     *
     * @param createId the value for jw_functional_dept.create_id
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_functional_dept.create_time
     *
     * @return the value of jw_functional_dept.create_time
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_functional_dept.create_time
     *
     * @param createTime the value for jw_functional_dept.create_time
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_functional_dept.updater_id
     *
     * @return the value of jw_functional_dept.updater_id
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_functional_dept.updater_id
     *
     * @param updaterId the value for jw_functional_dept.updater_id
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_functional_dept.update_time
     *
     * @return the value of jw_functional_dept.update_time
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_functional_dept.update_time
     *
     * @param updateTime the value for jw_functional_dept.update_time
     *
     * @mbggenerated Mon Apr 24 15:26:22 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}