package com.huaao.ejwplatform.mapper;

import com.huaao.ejwplatform.dao.JwAlertAppraise;
import com.huaao.ejwplatform.dao.JwAlertAppraiseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JwAlertAppraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_alert_appraise
     *
     * @mbggenerated Wed Apr 19 16:50:17 CST 2017
     */
    int countByExample(JwAlertAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_alert_appraise
     *
     * @mbggenerated Wed Apr 19 16:50:17 CST 2017
     */
    int deleteByExample(JwAlertAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_alert_appraise
     *
     * @mbggenerated Wed Apr 19 16:50:17 CST 2017
     */
    int deleteByPrimaryKey(String alertId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_alert_appraise
     *
     * @mbggenerated Wed Apr 19 16:50:17 CST 2017
     */
    int insert(JwAlertAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_alert_appraise
     *
     * @mbggenerated Wed Apr 19 16:50:17 CST 2017
     */
    int insertSelective(JwAlertAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_alert_appraise
     *
     * @mbggenerated Wed Apr 19 16:50:17 CST 2017
     */
    List<JwAlertAppraise> selectByExample(JwAlertAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_alert_appraise
     *
     * @mbggenerated Wed Apr 19 16:50:17 CST 2017
     */
    JwAlertAppraise selectByPrimaryKey(String alertId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_alert_appraise
     *
     * @mbggenerated Wed Apr 19 16:50:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") JwAlertAppraise record, @Param("example") JwAlertAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_alert_appraise
     *
     * @mbggenerated Wed Apr 19 16:50:17 CST 2017
     */
    int updateByExample(@Param("record") JwAlertAppraise record, @Param("example") JwAlertAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_alert_appraise
     *
     * @mbggenerated Wed Apr 19 16:50:17 CST 2017
     */
    int updateByPrimaryKeySelective(JwAlertAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_alert_appraise
     *
     * @mbggenerated Wed Apr 19 16:50:17 CST 2017
     */
    int updateByPrimaryKey(JwAlertAppraise record);
}