package com.huaao.ejwplatform.mapper;

import com.huaao.ejwplatform.dao.JwEmsArea;
import com.huaao.ejwplatform.dao.JwEmsAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JwEmsAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_area
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    int countByExample(JwEmsAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_area
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    int deleteByExample(JwEmsAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_area
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_area
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    int insert(JwEmsArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_area
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    int insertSelective(JwEmsArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_area
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    List<JwEmsArea> selectByExample(JwEmsAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_area
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    JwEmsArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_area
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") JwEmsArea record, @Param("example") JwEmsAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_area
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    int updateByExample(@Param("record") JwEmsArea record, @Param("example") JwEmsAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_area
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    int updateByPrimaryKeySelective(JwEmsArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_area
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    int updateByPrimaryKey(JwEmsArea record);
}