package com.huaao.ejwplatform.mapper;

import com.huaao.ejwplatform.dao.JwNotice;
import com.huaao.ejwplatform.dao.JwNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JwNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_notice
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    int countByExample(JwNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_notice
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    int deleteByExample(JwNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_notice
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_notice
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    int insert(JwNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_notice
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    int insertSelective(JwNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_notice
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    List<JwNotice> selectByExample(JwNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_notice
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    JwNotice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_notice
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") JwNotice record, @Param("example") JwNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_notice
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    int updateByExample(@Param("record") JwNotice record, @Param("example") JwNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_notice
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    int updateByPrimaryKeySelective(JwNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_notice
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    int updateByPrimaryKey(JwNotice record);
}