package com.huaao.ejwplatform.mapper;

import com.huaao.ejwplatform.dao.JwWater;
import com.huaao.ejwplatform.dao.JwWaterExample;
import com.huaao.ejwplatform.dao.JwWaterExampleExt;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JwWaterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_water
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int countByExample(JwWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_water
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int deleteByExample(JwWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_water
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_water
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int insert(JwWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_water
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int insertSelective(JwWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_water
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    List<JwWater> selectByExample(JwWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_water
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    JwWater selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_water
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") JwWater record, @Param("example") JwWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_water
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int updateByExample(@Param("record") JwWater record, @Param("example") JwWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_water
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int updateByPrimaryKeySelective(JwWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_water
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int updateByPrimaryKey(JwWater record);
    
	int countMultiByExample(JwWaterExampleExt exa);

	List<JwWater> selectMultiByExample(JwWaterExampleExt exa);
	
    int addWaterRecordBatch(List<JwWater> jwWaterList); 
}