package com.huaao.ejwplatform.mapper;

import com.huaao.ejwplatform.dao.SysDept;
import com.huaao.ejwplatform.dao.SysDeptExample;
import com.huaao.ejwplatform.dao.SysDeptWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int countByExample(SysDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int deleteByExample(SysDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int insert(SysDeptWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int insertSelective(SysDeptWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    List<SysDeptWithBLOBs> selectByExampleWithBLOBs(SysDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
//    List<SysDept> selectByExample(SysDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    SysDeptWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysDeptWithBLOBs record, @Param("example") SysDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") SysDeptWithBLOBs record, @Param("example") SysDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
//    int updateByExample(@Param("record") SysDept record, @Param("example") SysDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int updateByPrimaryKeySelective(SysDeptWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(SysDeptWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbggenerated Wed May 24 11:30:10 CST 2017
     */
//    int updateByPrimaryKey(SysDept record);
}