package com.huaao.ejwplatform.dao;

import java.io.Serializable;
import java.util.Date;

public class JwCriminalRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.id
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.user_id
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.idcard_no
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String idcardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.name
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.unit_name
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String unitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.target
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.create_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.police_id
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String policeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.police_name
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String policeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.police_phone
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String policePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.finish_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private Date finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.user_phone
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.status
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.print_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private Date printTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.address
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.auth_status
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private Integer authStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.has_record
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private Integer hasRecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.auth_desc
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String authDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.res_address
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String resAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.idcard_img1
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String idcardImg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.idcard_img2
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String idcardImg2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.attachment
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String attachment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.dept_id
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.type
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.update_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.recieve_type
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private Integer recieveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.print_idcrad
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String printIdcrad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.qrcode
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String qrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.invalid_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private Date invalidTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.receiver_name
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_criminal_record.audit_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jw_criminal_record
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.id
     *
     * @return the value of jw_criminal_record.id
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.id
     *
     * @param id the value for jw_criminal_record.id
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.user_id
     *
     * @return the value of jw_criminal_record.user_id
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.user_id
     *
     * @param userId the value for jw_criminal_record.user_id
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.idcard_no
     *
     * @return the value of jw_criminal_record.idcard_no
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getIdcardNo() {
        return idcardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.idcard_no
     *
     * @param idcardNo the value for jw_criminal_record.idcard_no
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setIdcardNo(String idcardNo) {
        this.idcardNo = idcardNo == null ? null : idcardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.name
     *
     * @return the value of jw_criminal_record.name
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.name
     *
     * @param name the value for jw_criminal_record.name
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.unit_name
     *
     * @return the value of jw_criminal_record.unit_name
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.unit_name
     *
     * @param unitName the value for jw_criminal_record.unit_name
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.target
     *
     * @return the value of jw_criminal_record.target
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.target
     *
     * @param target the value for jw_criminal_record.target
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.create_time
     *
     * @return the value of jw_criminal_record.create_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.create_time
     *
     * @param createTime the value for jw_criminal_record.create_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.police_id
     *
     * @return the value of jw_criminal_record.police_id
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getPoliceId() {
        return policeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.police_id
     *
     * @param policeId the value for jw_criminal_record.police_id
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setPoliceId(String policeId) {
        this.policeId = policeId == null ? null : policeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.police_name
     *
     * @return the value of jw_criminal_record.police_name
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getPoliceName() {
        return policeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.police_name
     *
     * @param policeName the value for jw_criminal_record.police_name
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setPoliceName(String policeName) {
        this.policeName = policeName == null ? null : policeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.police_phone
     *
     * @return the value of jw_criminal_record.police_phone
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getPolicePhone() {
        return policePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.police_phone
     *
     * @param policePhone the value for jw_criminal_record.police_phone
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setPolicePhone(String policePhone) {
        this.policePhone = policePhone == null ? null : policePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.finish_time
     *
     * @return the value of jw_criminal_record.finish_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.finish_time
     *
     * @param finishTime the value for jw_criminal_record.finish_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.user_phone
     *
     * @return the value of jw_criminal_record.user_phone
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.user_phone
     *
     * @param userPhone the value for jw_criminal_record.user_phone
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.status
     *
     * @return the value of jw_criminal_record.status
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.status
     *
     * @param status the value for jw_criminal_record.status
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.print_time
     *
     * @return the value of jw_criminal_record.print_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public Date getPrintTime() {
        return printTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.print_time
     *
     * @param printTime the value for jw_criminal_record.print_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setPrintTime(Date printTime) {
        this.printTime = printTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.address
     *
     * @return the value of jw_criminal_record.address
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.address
     *
     * @param address the value for jw_criminal_record.address
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.auth_status
     *
     * @return the value of jw_criminal_record.auth_status
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public Integer getAuthStatus() {
        return authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.auth_status
     *
     * @param authStatus the value for jw_criminal_record.auth_status
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setAuthStatus(Integer authStatus) {
        this.authStatus = authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.has_record
     *
     * @return the value of jw_criminal_record.has_record
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public Integer getHasRecord() {
        return hasRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.has_record
     *
     * @param hasRecord the value for jw_criminal_record.has_record
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setHasRecord(Integer hasRecord) {
        this.hasRecord = hasRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.auth_desc
     *
     * @return the value of jw_criminal_record.auth_desc
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getAuthDesc() {
        return authDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.auth_desc
     *
     * @param authDesc the value for jw_criminal_record.auth_desc
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setAuthDesc(String authDesc) {
        this.authDesc = authDesc == null ? null : authDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.res_address
     *
     * @return the value of jw_criminal_record.res_address
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getResAddress() {
        return resAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.res_address
     *
     * @param resAddress the value for jw_criminal_record.res_address
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setResAddress(String resAddress) {
        this.resAddress = resAddress == null ? null : resAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.idcard_img1
     *
     * @return the value of jw_criminal_record.idcard_img1
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getIdcardImg1() {
        return idcardImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.idcard_img1
     *
     * @param idcardImg1 the value for jw_criminal_record.idcard_img1
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setIdcardImg1(String idcardImg1) {
        this.idcardImg1 = idcardImg1 == null ? null : idcardImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.idcard_img2
     *
     * @return the value of jw_criminal_record.idcard_img2
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getIdcardImg2() {
        return idcardImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.idcard_img2
     *
     * @param idcardImg2 the value for jw_criminal_record.idcard_img2
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setIdcardImg2(String idcardImg2) {
        this.idcardImg2 = idcardImg2 == null ? null : idcardImg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.attachment
     *
     * @return the value of jw_criminal_record.attachment
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.attachment
     *
     * @param attachment the value for jw_criminal_record.attachment
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment == null ? null : attachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.dept_id
     *
     * @return the value of jw_criminal_record.dept_id
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.dept_id
     *
     * @param deptId the value for jw_criminal_record.dept_id
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.type
     *
     * @return the value of jw_criminal_record.type
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.type
     *
     * @param type the value for jw_criminal_record.type
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.update_time
     *
     * @return the value of jw_criminal_record.update_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.update_time
     *
     * @param updateTime the value for jw_criminal_record.update_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.recieve_type
     *
     * @return the value of jw_criminal_record.recieve_type
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public Integer getRecieveType() {
        return recieveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.recieve_type
     *
     * @param recieveType the value for jw_criminal_record.recieve_type
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setRecieveType(Integer recieveType) {
        this.recieveType = recieveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.print_idcrad
     *
     * @return the value of jw_criminal_record.print_idcrad
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getPrintIdcrad() {
        return printIdcrad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.print_idcrad
     *
     * @param printIdcrad the value for jw_criminal_record.print_idcrad
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setPrintIdcrad(String printIdcrad) {
        this.printIdcrad = printIdcrad == null ? null : printIdcrad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.qrcode
     *
     * @return the value of jw_criminal_record.qrcode
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.qrcode
     *
     * @param qrcode the value for jw_criminal_record.qrcode
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode == null ? null : qrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.invalid_time
     *
     * @return the value of jw_criminal_record.invalid_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public Date getInvalidTime() {
        return invalidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.invalid_time
     *
     * @param invalidTime the value for jw_criminal_record.invalid_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setInvalidTime(Date invalidTime) {
        this.invalidTime = invalidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.receiver_name
     *
     * @return the value of jw_criminal_record.receiver_name
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.receiver_name
     *
     * @param receiverName the value for jw_criminal_record.receiver_name
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_criminal_record.audit_time
     *
     * @return the value of jw_criminal_record.audit_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_criminal_record.audit_time
     *
     * @param auditTime the value for jw_criminal_record.audit_time
     *
     * @mbggenerated Thu Apr 20 11:53:03 CST 2017
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }
}