package com.huaao.ejwplatform.mapper;

import com.huaao.ejwplatform.dao.JwElectricity;
import com.huaao.ejwplatform.dao.JwElectricityExample;
import com.huaao.ejwplatform.dao.JwElectricityExampleExt;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JwElectricityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_electricity
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int countByExample(JwElectricityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_electricity
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int deleteByExample(JwElectricityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_electricity
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_electricity
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int insert(JwElectricity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_electricity
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int insertSelective(JwElectricity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_electricity
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    List<JwElectricity> selectByExample(JwElectricityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_electricity
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    JwElectricity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_electricity
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") JwElectricity record, @Param("example") JwElectricityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_electricity
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int updateByExample(@Param("record") JwElectricity record, @Param("example") JwElectricityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_electricity
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int updateByPrimaryKeySelective(JwElectricity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_electricity
     *
     * @mbggenerated Thu May 25 14:10:31 CST 2017
     */
    int updateByPrimaryKey(JwElectricity record);
    
	int countMultiByExample(JwElectricityExampleExt exa);

	List<JwElectricity> selectMultiByExample(JwElectricityExampleExt exa);
	
	int addJwElectricityRecordBatch(List<JwElectricity> jwElectricityList); 
}