package com.huaao.ejwplatform.dao;

import java.io.Serializable;
import java.util.Date;

public class JwNotice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_notice.id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_notice.user_id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_notice.type
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_notice.msg_id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private String msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_notice.time
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_notice.title
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_notice.message
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_notice.room_id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private String roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_notice.room_name
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private String roomName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_notice.room_pwd
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private String roomPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_notice.creator_id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_notice.create_time
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_notice.updater_id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private String updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_notice.update_time
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_notice.status
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_notice.msg
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jw_notice
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_notice.id
     *
     * @return the value of jw_notice.id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_notice.id
     *
     * @param id the value for jw_notice.id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_notice.user_id
     *
     * @return the value of jw_notice.user_id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_notice.user_id
     *
     * @param userId the value for jw_notice.user_id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_notice.type
     *
     * @return the value of jw_notice.type
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_notice.type
     *
     * @param type the value for jw_notice.type
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_notice.msg_id
     *
     * @return the value of jw_notice.msg_id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_notice.msg_id
     *
     * @param msgId the value for jw_notice.msg_id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId == null ? null : msgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_notice.time
     *
     * @return the value of jw_notice.time
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_notice.time
     *
     * @param time the value for jw_notice.time
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_notice.title
     *
     * @return the value of jw_notice.title
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_notice.title
     *
     * @param title the value for jw_notice.title
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_notice.message
     *
     * @return the value of jw_notice.message
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_notice.message
     *
     * @param message the value for jw_notice.message
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_notice.room_id
     *
     * @return the value of jw_notice.room_id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_notice.room_id
     *
     * @param roomId the value for jw_notice.room_id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public void setRoomId(String roomId) {
        this.roomId = roomId == null ? null : roomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_notice.room_name
     *
     * @return the value of jw_notice.room_name
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_notice.room_name
     *
     * @param roomName the value for jw_notice.room_name
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public void setRoomName(String roomName) {
        this.roomName = roomName == null ? null : roomName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_notice.room_pwd
     *
     * @return the value of jw_notice.room_pwd
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public String getRoomPwd() {
        return roomPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_notice.room_pwd
     *
     * @param roomPwd the value for jw_notice.room_pwd
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public void setRoomPwd(String roomPwd) {
        this.roomPwd = roomPwd == null ? null : roomPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_notice.creator_id
     *
     * @return the value of jw_notice.creator_id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_notice.creator_id
     *
     * @param creatorId the value for jw_notice.creator_id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_notice.create_time
     *
     * @return the value of jw_notice.create_time
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_notice.create_time
     *
     * @param createTime the value for jw_notice.create_time
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_notice.updater_id
     *
     * @return the value of jw_notice.updater_id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_notice.updater_id
     *
     * @param updaterId the value for jw_notice.updater_id
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_notice.update_time
     *
     * @return the value of jw_notice.update_time
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_notice.update_time
     *
     * @param updateTime the value for jw_notice.update_time
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_notice.status
     *
     * @return the value of jw_notice.status
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_notice.status
     *
     * @param status the value for jw_notice.status
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_notice.msg
     *
     * @return the value of jw_notice.msg
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_notice.msg
     *
     * @param msg the value for jw_notice.msg
     *
     * @mbggenerated Thu Apr 06 10:38:04 CST 2017
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }
}