package com.huaao.ejwplatform.mapper;

import com.huaao.ejwplatform.dao.JwEms;
import com.huaao.ejwplatform.dao.JwEmsExample;
import com.huaao.ejwplatform.dao.JwEmsExt;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JwEmsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    int countByExample(JwEmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    int deleteByExample(JwEmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    int insert(JwEms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    int insertSelective(JwEms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    List<JwEms> selectByExample(JwEmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    JwEms selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") JwEms record, @Param("example") JwEmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    int updateByExample(@Param("record") JwEms record, @Param("example") JwEmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    int updateByPrimaryKeySelective(JwEms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    int updateByPrimaryKey(JwEms record);
}