package com.huaao.ejwplatform.mapper;

import com.huaao.ejwplatform.dao.SysLogsLogin;
import com.huaao.ejwplatform.dao.SysLogsLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysLogsLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_login
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    int countByExample(SysLogsLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_login
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    int deleteByExample(SysLogsLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_login
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    int insert(SysLogsLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_login
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    int insertSelective(SysLogsLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_login
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    List<SysLogsLogin> selectByExample(SysLogsLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_login
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysLogsLogin record, @Param("example") SysLogsLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_login
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    int updateByExample(@Param("record") SysLogsLogin record, @Param("example") SysLogsLoginExample example);
}