package com.huaao.ejwplatform.dao;

import java.util.ArrayList;
import java.util.List;

public class JwEmsStatusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jw_ems_status
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jw_ems_status
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jw_ems_status
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_status
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    public JwEmsStatusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_status
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_status
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_status
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_status
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_status
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_status
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_status
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_status
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_status
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_ems_status
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jw_ems_status
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMailNumIsNull() {
            addCriterion("mail_num is null");
            return (Criteria) this;
        }

        public Criteria andMailNumIsNotNull() {
            addCriterion("mail_num is not null");
            return (Criteria) this;
        }

        public Criteria andMailNumEqualTo(String value) {
            addCriterion("mail_num =", value, "mailNum");
            return (Criteria) this;
        }

        public Criteria andMailNumNotEqualTo(String value) {
            addCriterion("mail_num <>", value, "mailNum");
            return (Criteria) this;
        }

        public Criteria andMailNumGreaterThan(String value) {
            addCriterion("mail_num >", value, "mailNum");
            return (Criteria) this;
        }

        public Criteria andMailNumGreaterThanOrEqualTo(String value) {
            addCriterion("mail_num >=", value, "mailNum");
            return (Criteria) this;
        }

        public Criteria andMailNumLessThan(String value) {
            addCriterion("mail_num <", value, "mailNum");
            return (Criteria) this;
        }

        public Criteria andMailNumLessThanOrEqualTo(String value) {
            addCriterion("mail_num <=", value, "mailNum");
            return (Criteria) this;
        }

        public Criteria andMailNumLike(String value) {
            addCriterion("mail_num like", value, "mailNum");
            return (Criteria) this;
        }

        public Criteria andMailNumNotLike(String value) {
            addCriterion("mail_num not like", value, "mailNum");
            return (Criteria) this;
        }

        public Criteria andMailNumIn(List<String> values) {
            addCriterion("mail_num in", values, "mailNum");
            return (Criteria) this;
        }

        public Criteria andMailNumNotIn(List<String> values) {
            addCriterion("mail_num not in", values, "mailNum");
            return (Criteria) this;
        }

        public Criteria andMailNumBetween(String value1, String value2) {
            addCriterion("mail_num between", value1, value2, "mailNum");
            return (Criteria) this;
        }

        public Criteria andMailNumNotBetween(String value1, String value2) {
            addCriterion("mail_num not between", value1, value2, "mailNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumberIsNull() {
            addCriterion("serial_number is null");
            return (Criteria) this;
        }

        public Criteria andSerialNumberIsNotNull() {
            addCriterion("serial_number is not null");
            return (Criteria) this;
        }

        public Criteria andSerialNumberEqualTo(String value) {
            addCriterion("serial_number =", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberNotEqualTo(String value) {
            addCriterion("serial_number <>", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberGreaterThan(String value) {
            addCriterion("serial_number >", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberGreaterThanOrEqualTo(String value) {
            addCriterion("serial_number >=", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberLessThan(String value) {
            addCriterion("serial_number <", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberLessThanOrEqualTo(String value) {
            addCriterion("serial_number <=", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberLike(String value) {
            addCriterion("serial_number like", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberNotLike(String value) {
            addCriterion("serial_number not like", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberIn(List<String> values) {
            addCriterion("serial_number in", values, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberNotIn(List<String> values) {
            addCriterion("serial_number not in", values, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberBetween(String value1, String value2) {
            addCriterion("serial_number between", value1, value2, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberNotBetween(String value1, String value2) {
            addCriterion("serial_number not between", value1, value2, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andProcdateIsNull() {
            addCriterion("procdate is null");
            return (Criteria) this;
        }

        public Criteria andProcdateIsNotNull() {
            addCriterion("procdate is not null");
            return (Criteria) this;
        }

        public Criteria andProcdateEqualTo(String value) {
            addCriterion("procdate =", value, "procdate");
            return (Criteria) this;
        }

        public Criteria andProcdateNotEqualTo(String value) {
            addCriterion("procdate <>", value, "procdate");
            return (Criteria) this;
        }

        public Criteria andProcdateGreaterThan(String value) {
            addCriterion("procdate >", value, "procdate");
            return (Criteria) this;
        }

        public Criteria andProcdateGreaterThanOrEqualTo(String value) {
            addCriterion("procdate >=", value, "procdate");
            return (Criteria) this;
        }

        public Criteria andProcdateLessThan(String value) {
            addCriterion("procdate <", value, "procdate");
            return (Criteria) this;
        }

        public Criteria andProcdateLessThanOrEqualTo(String value) {
            addCriterion("procdate <=", value, "procdate");
            return (Criteria) this;
        }

        public Criteria andProcdateLike(String value) {
            addCriterion("procdate like", value, "procdate");
            return (Criteria) this;
        }

        public Criteria andProcdateNotLike(String value) {
            addCriterion("procdate not like", value, "procdate");
            return (Criteria) this;
        }

        public Criteria andProcdateIn(List<String> values) {
            addCriterion("procdate in", values, "procdate");
            return (Criteria) this;
        }

        public Criteria andProcdateNotIn(List<String> values) {
            addCriterion("procdate not in", values, "procdate");
            return (Criteria) this;
        }

        public Criteria andProcdateBetween(String value1, String value2) {
            addCriterion("procdate between", value1, value2, "procdate");
            return (Criteria) this;
        }

        public Criteria andProcdateNotBetween(String value1, String value2) {
            addCriterion("procdate not between", value1, value2, "procdate");
            return (Criteria) this;
        }

        public Criteria andProctimeIsNull() {
            addCriterion("proctime is null");
            return (Criteria) this;
        }

        public Criteria andProctimeIsNotNull() {
            addCriterion("proctime is not null");
            return (Criteria) this;
        }

        public Criteria andProctimeEqualTo(String value) {
            addCriterion("proctime =", value, "proctime");
            return (Criteria) this;
        }

        public Criteria andProctimeNotEqualTo(String value) {
            addCriterion("proctime <>", value, "proctime");
            return (Criteria) this;
        }

        public Criteria andProctimeGreaterThan(String value) {
            addCriterion("proctime >", value, "proctime");
            return (Criteria) this;
        }

        public Criteria andProctimeGreaterThanOrEqualTo(String value) {
            addCriterion("proctime >=", value, "proctime");
            return (Criteria) this;
        }

        public Criteria andProctimeLessThan(String value) {
            addCriterion("proctime <", value, "proctime");
            return (Criteria) this;
        }

        public Criteria andProctimeLessThanOrEqualTo(String value) {
            addCriterion("proctime <=", value, "proctime");
            return (Criteria) this;
        }

        public Criteria andProctimeLike(String value) {
            addCriterion("proctime like", value, "proctime");
            return (Criteria) this;
        }

        public Criteria andProctimeNotLike(String value) {
            addCriterion("proctime not like", value, "proctime");
            return (Criteria) this;
        }

        public Criteria andProctimeIn(List<String> values) {
            addCriterion("proctime in", values, "proctime");
            return (Criteria) this;
        }

        public Criteria andProctimeNotIn(List<String> values) {
            addCriterion("proctime not in", values, "proctime");
            return (Criteria) this;
        }

        public Criteria andProctimeBetween(String value1, String value2) {
            addCriterion("proctime between", value1, value2, "proctime");
            return (Criteria) this;
        }

        public Criteria andProctimeNotBetween(String value1, String value2) {
            addCriterion("proctime not between", value1, value2, "proctime");
            return (Criteria) this;
        }

        public Criteria andOrgFullNameIsNull() {
            addCriterion("org_full_name is null");
            return (Criteria) this;
        }

        public Criteria andOrgFullNameIsNotNull() {
            addCriterion("org_full_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrgFullNameEqualTo(String value) {
            addCriterion("org_full_name =", value, "orgFullName");
            return (Criteria) this;
        }

        public Criteria andOrgFullNameNotEqualTo(String value) {
            addCriterion("org_full_name <>", value, "orgFullName");
            return (Criteria) this;
        }

        public Criteria andOrgFullNameGreaterThan(String value) {
            addCriterion("org_full_name >", value, "orgFullName");
            return (Criteria) this;
        }

        public Criteria andOrgFullNameGreaterThanOrEqualTo(String value) {
            addCriterion("org_full_name >=", value, "orgFullName");
            return (Criteria) this;
        }

        public Criteria andOrgFullNameLessThan(String value) {
            addCriterion("org_full_name <", value, "orgFullName");
            return (Criteria) this;
        }

        public Criteria andOrgFullNameLessThanOrEqualTo(String value) {
            addCriterion("org_full_name <=", value, "orgFullName");
            return (Criteria) this;
        }

        public Criteria andOrgFullNameLike(String value) {
            addCriterion("org_full_name like", value, "orgFullName");
            return (Criteria) this;
        }

        public Criteria andOrgFullNameNotLike(String value) {
            addCriterion("org_full_name not like", value, "orgFullName");
            return (Criteria) this;
        }

        public Criteria andOrgFullNameIn(List<String> values) {
            addCriterion("org_full_name in", values, "orgFullName");
            return (Criteria) this;
        }

        public Criteria andOrgFullNameNotIn(List<String> values) {
            addCriterion("org_full_name not in", values, "orgFullName");
            return (Criteria) this;
        }

        public Criteria andOrgFullNameBetween(String value1, String value2) {
            addCriterion("org_full_name between", value1, value2, "orgFullName");
            return (Criteria) this;
        }

        public Criteria andOrgFullNameNotBetween(String value1, String value2) {
            addCriterion("org_full_name not between", value1, value2, "orgFullName");
            return (Criteria) this;
        }

        public Criteria andActionIsNull() {
            addCriterion("action is null");
            return (Criteria) this;
        }

        public Criteria andActionIsNotNull() {
            addCriterion("action is not null");
            return (Criteria) this;
        }

        public Criteria andActionEqualTo(String value) {
            addCriterion("action =", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotEqualTo(String value) {
            addCriterion("action <>", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionGreaterThan(String value) {
            addCriterion("action >", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionGreaterThanOrEqualTo(String value) {
            addCriterion("action >=", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionLessThan(String value) {
            addCriterion("action <", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionLessThanOrEqualTo(String value) {
            addCriterion("action <=", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionLike(String value) {
            addCriterion("action like", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotLike(String value) {
            addCriterion("action not like", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionIn(List<String> values) {
            addCriterion("action in", values, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotIn(List<String> values) {
            addCriterion("action not in", values, "action");
            return (Criteria) this;
        }

        public Criteria andActionBetween(String value1, String value2) {
            addCriterion("action between", value1, value2, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotBetween(String value1, String value2) {
            addCriterion("action not between", value1, value2, "action");
            return (Criteria) this;
        }

        public Criteria andProperDeliveryIsNull() {
            addCriterion("proper_delivery is null");
            return (Criteria) this;
        }

        public Criteria andProperDeliveryIsNotNull() {
            addCriterion("proper_delivery is not null");
            return (Criteria) this;
        }

        public Criteria andProperDeliveryEqualTo(String value) {
            addCriterion("proper_delivery =", value, "properDelivery");
            return (Criteria) this;
        }

        public Criteria andProperDeliveryNotEqualTo(String value) {
            addCriterion("proper_delivery <>", value, "properDelivery");
            return (Criteria) this;
        }

        public Criteria andProperDeliveryGreaterThan(String value) {
            addCriterion("proper_delivery >", value, "properDelivery");
            return (Criteria) this;
        }

        public Criteria andProperDeliveryGreaterThanOrEqualTo(String value) {
            addCriterion("proper_delivery >=", value, "properDelivery");
            return (Criteria) this;
        }

        public Criteria andProperDeliveryLessThan(String value) {
            addCriterion("proper_delivery <", value, "properDelivery");
            return (Criteria) this;
        }

        public Criteria andProperDeliveryLessThanOrEqualTo(String value) {
            addCriterion("proper_delivery <=", value, "properDelivery");
            return (Criteria) this;
        }

        public Criteria andProperDeliveryLike(String value) {
            addCriterion("proper_delivery like", value, "properDelivery");
            return (Criteria) this;
        }

        public Criteria andProperDeliveryNotLike(String value) {
            addCriterion("proper_delivery not like", value, "properDelivery");
            return (Criteria) this;
        }

        public Criteria andProperDeliveryIn(List<String> values) {
            addCriterion("proper_delivery in", values, "properDelivery");
            return (Criteria) this;
        }

        public Criteria andProperDeliveryNotIn(List<String> values) {
            addCriterion("proper_delivery not in", values, "properDelivery");
            return (Criteria) this;
        }

        public Criteria andProperDeliveryBetween(String value1, String value2) {
            addCriterion("proper_delivery between", value1, value2, "properDelivery");
            return (Criteria) this;
        }

        public Criteria andProperDeliveryNotBetween(String value1, String value2) {
            addCriterion("proper_delivery not between", value1, value2, "properDelivery");
            return (Criteria) this;
        }

        public Criteria andNotProperDeliveryIsNull() {
            addCriterion("not_proper_delivery is null");
            return (Criteria) this;
        }

        public Criteria andNotProperDeliveryIsNotNull() {
            addCriterion("not_proper_delivery is not null");
            return (Criteria) this;
        }

        public Criteria andNotProperDeliveryEqualTo(String value) {
            addCriterion("not_proper_delivery =", value, "notProperDelivery");
            return (Criteria) this;
        }

        public Criteria andNotProperDeliveryNotEqualTo(String value) {
            addCriterion("not_proper_delivery <>", value, "notProperDelivery");
            return (Criteria) this;
        }

        public Criteria andNotProperDeliveryGreaterThan(String value) {
            addCriterion("not_proper_delivery >", value, "notProperDelivery");
            return (Criteria) this;
        }

        public Criteria andNotProperDeliveryGreaterThanOrEqualTo(String value) {
            addCriterion("not_proper_delivery >=", value, "notProperDelivery");
            return (Criteria) this;
        }

        public Criteria andNotProperDeliveryLessThan(String value) {
            addCriterion("not_proper_delivery <", value, "notProperDelivery");
            return (Criteria) this;
        }

        public Criteria andNotProperDeliveryLessThanOrEqualTo(String value) {
            addCriterion("not_proper_delivery <=", value, "notProperDelivery");
            return (Criteria) this;
        }

        public Criteria andNotProperDeliveryLike(String value) {
            addCriterion("not_proper_delivery like", value, "notProperDelivery");
            return (Criteria) this;
        }

        public Criteria andNotProperDeliveryNotLike(String value) {
            addCriterion("not_proper_delivery not like", value, "notProperDelivery");
            return (Criteria) this;
        }

        public Criteria andNotProperDeliveryIn(List<String> values) {
            addCriterion("not_proper_delivery in", values, "notProperDelivery");
            return (Criteria) this;
        }

        public Criteria andNotProperDeliveryNotIn(List<String> values) {
            addCriterion("not_proper_delivery not in", values, "notProperDelivery");
            return (Criteria) this;
        }

        public Criteria andNotProperDeliveryBetween(String value1, String value2) {
            addCriterion("not_proper_delivery between", value1, value2, "notProperDelivery");
            return (Criteria) this;
        }

        public Criteria andNotProperDeliveryNotBetween(String value1, String value2) {
            addCriterion("not_proper_delivery not between", value1, value2, "notProperDelivery");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andEffectIsNull() {
            addCriterion("effect is null");
            return (Criteria) this;
        }

        public Criteria andEffectIsNotNull() {
            addCriterion("effect is not null");
            return (Criteria) this;
        }

        public Criteria andEffectEqualTo(Integer value) {
            addCriterion("effect =", value, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectNotEqualTo(Integer value) {
            addCriterion("effect <>", value, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectGreaterThan(Integer value) {
            addCriterion("effect >", value, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectGreaterThanOrEqualTo(Integer value) {
            addCriterion("effect >=", value, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectLessThan(Integer value) {
            addCriterion("effect <", value, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectLessThanOrEqualTo(Integer value) {
            addCriterion("effect <=", value, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectIn(List<Integer> values) {
            addCriterion("effect in", values, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectNotIn(List<Integer> values) {
            addCriterion("effect not in", values, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectBetween(Integer value1, Integer value2) {
            addCriterion("effect between", value1, value2, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectNotBetween(Integer value1, Integer value2) {
            addCriterion("effect not between", value1, value2, "effect");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jw_ems_status
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 27 17:14:43 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jw_ems_status
     *
     * @mbggenerated Mon Mar 27 17:14:43 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}