package com.huaao.ejwplatform.dao;

import java.io.Serializable;

public class JwEmsArea implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_area.id
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_area.parent_id
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_area.name
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_area.merger_name
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private String mergerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_area.short_name
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_area.merger_short_name
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private String mergerShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_area.level_type
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private Integer levelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_area.city_code
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_area.zip_code
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_area.pinyin
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_area.jianpin
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private String jianpin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_area.firstchar
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private String firstchar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_area.lng
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_area.lat
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_area.remarks
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jw_ems_area.is_leaf
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private boolean isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jw_ems_area
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_area.id
     *
     * @return the value of jw_ems_area.id
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_area.id
     *
     * @param id the value for jw_ems_area.id
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_area.parent_id
     *
     * @return the value of jw_ems_area.parent_id
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_area.parent_id
     *
     * @param parentId the value for jw_ems_area.parent_id
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_area.name
     *
     * @return the value of jw_ems_area.name
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_area.name
     *
     * @param name the value for jw_ems_area.name
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_area.merger_name
     *
     * @return the value of jw_ems_area.merger_name
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public String getMergerName() {
        return mergerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_area.merger_name
     *
     * @param mergerName the value for jw_ems_area.merger_name
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public void setMergerName(String mergerName) {
        this.mergerName = mergerName == null ? null : mergerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_area.short_name
     *
     * @return the value of jw_ems_area.short_name
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_area.short_name
     *
     * @param shortName the value for jw_ems_area.short_name
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_area.merger_short_name
     *
     * @return the value of jw_ems_area.merger_short_name
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public String getMergerShortName() {
        return mergerShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_area.merger_short_name
     *
     * @param mergerShortName the value for jw_ems_area.merger_short_name
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public void setMergerShortName(String mergerShortName) {
        this.mergerShortName = mergerShortName == null ? null : mergerShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_area.level_type
     *
     * @return the value of jw_ems_area.level_type
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public Integer getLevelType() {
        return levelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_area.level_type
     *
     * @param levelType the value for jw_ems_area.level_type
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public void setLevelType(Integer levelType) {
        this.levelType = levelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_area.city_code
     *
     * @return the value of jw_ems_area.city_code
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_area.city_code
     *
     * @param cityCode the value for jw_ems_area.city_code
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_area.zip_code
     *
     * @return the value of jw_ems_area.zip_code
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_area.zip_code
     *
     * @param zipCode the value for jw_ems_area.zip_code
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_area.pinyin
     *
     * @return the value of jw_ems_area.pinyin
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_area.pinyin
     *
     * @param pinyin the value for jw_ems_area.pinyin
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_area.jianpin
     *
     * @return the value of jw_ems_area.jianpin
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public String getJianpin() {
        return jianpin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_area.jianpin
     *
     * @param jianpin the value for jw_ems_area.jianpin
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public void setJianpin(String jianpin) {
        this.jianpin = jianpin == null ? null : jianpin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_area.firstchar
     *
     * @return the value of jw_ems_area.firstchar
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public String getFirstchar() {
        return firstchar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_area.firstchar
     *
     * @param firstchar the value for jw_ems_area.firstchar
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public void setFirstchar(String firstchar) {
        this.firstchar = firstchar == null ? null : firstchar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_area.lng
     *
     * @return the value of jw_ems_area.lng
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_area.lng
     *
     * @param lng the value for jw_ems_area.lng
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_area.lat
     *
     * @return the value of jw_ems_area.lat
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_area.lat
     *
     * @param lat the value for jw_ems_area.lat
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_area.remarks
     *
     * @return the value of jw_ems_area.remarks
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_area.remarks
     *
     * @param remarks the value for jw_ems_area.remarks
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jw_ems_area.is_leaf
     *
     * @return the value of jw_ems_area.is_leaf
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public boolean isIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jw_ems_area.is_leaf
     *
     * @param isLeaf the value for jw_ems_area.is_leaf
     *
     * @mbggenerated Thu Apr 20 10:46:55 CST 2017
     */
    public void setIsLeaf(boolean isLeaf) {
        this.isLeaf = isLeaf;
    }
}