package com.huaao.ejwplatform.dao;

import java.io.Serializable;
import java.util.Date;

public class SysLogsLogin implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs_login.id
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs_login.cellphone
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    private String cellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs_login.create_time
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs_login.info
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_logs_login
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs_login.id
     *
     * @return the value of sys_logs_login.id
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs_login.id
     *
     * @param id the value for sys_logs_login.id
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs_login.cellphone
     *
     * @return the value of sys_logs_login.cellphone
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs_login.cellphone
     *
     * @param cellphone the value for sys_logs_login.cellphone
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone == null ? null : cellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs_login.create_time
     *
     * @return the value of sys_logs_login.create_time
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs_login.create_time
     *
     * @param createTime the value for sys_logs_login.create_time
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs_login.info
     *
     * @return the value of sys_logs_login.info
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs_login.info
     *
     * @param info the value for sys_logs_login.info
     *
     * @mbggenerated Tue May 23 11:13:33 CST 2017
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }
}