package com.huaao.ejwplatform.dao;

import java.io.Serializable;

public class UserTest implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.id
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.account
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.password
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_test
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.id
     *
     * @return the value of user_test.id
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.id
     *
     * @param id the value for user_test.id
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.account
     *
     * @return the value of user_test.account
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.account
     *
     * @param account the value for user_test.account
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.password
     *
     * @return the value of user_test.password
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.password
     *
     * @param password the value for user_test.password
     *
     * @mbggenerated Tue Dec 27 14:23:08 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}